# Generated by Django 3.0.6 on 2020-06-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblogsdatabase',
            name='blogInfo',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
