# Generated by Django 3.0.6 on 2020-06-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userBlog', '0002_myblogsdatabase_bloginfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblogsdatabase',
            name='blogContent',
            field=models.TextField(max_length=10000),
        ),
    ]
