# Generated by Django 3.0.6 on 2020-06-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userBlog', '0004_contactdatabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblogsdatabase',
            name='author',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
