# Generated by Django 3.0.6 on 2020-06-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userBlog', '0005_myblogsdatabase_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblogsdatabase',
            name='blogContent',
            field=models.TextField(max_length=15000),
        ),
    ]
